
repeat = 1
import time

while repeat == 1:
    print("Baka")
    time.sleep(0.1)
    print("Baka")
    time.sleep(0.1)
    print("Baka")
    time.sleep(0.1)
    print("Baka")
    time.sleep(0.1)
    print("Baka")
    time.sleep(0.1)
    print("Baka")
    time.sleep(0.1)
    print("bAka")
    time.sleep(0.1)
    print("bAka")
    time.sleep(0.1)
    print("bAka")
    time.sleep(0.1)
    print("bAka")
    time.sleep(0.1)
    print("bAka")
    time.sleep(0.1)
    print("bAka")
    time.sleep(0.1)
    print("baKa")
    time.sleep(0.1)
    print("baKa")
    time.sleep(0.1)
    print("baKa")
    time.sleep(0.1)
    print("baKa")
    time.sleep(0.1)
    print("baKa")
    time.sleep(0.1)
    print("baKa")
    time.sleep(0.1)
    print("bakA")
    time.sleep(0.1)
    print("bakA")
    time.sleep(0.1)
    print("bakA")
    time.sleep(0.1)
    print("bakA")
    time.sleep(0.1)
    print("bakA")
    time.sleep(0.1)
    print("bakA")
    time.sleep(0.1)





